os:
  - linux
language: node_js
node_js:
  - "10.16.0"
install:
  - "yarn"
script:
  - "yarn build"
  - "yarn release"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
env:
  - YARN_GPG=no
